apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 5
  strategy:
    rollingUpdate: 
      maxSurge: 3
      maxUnavailable: 1
  template:
    spec:
      containers:
        - name: hemlo